install awscli
install bat
install coreutils
install diff-so-fancy
install git
install git-lfs
install gnupg
install htop
install libxml2
install mysql
install n
install openssh
install pinentry-mac
install postgresql
install puma/puma/puma-dev
install ranger
install rbenv
install redis
install svgo
install vim
install watchman
install wget
install yarn
install zsh
